### ISSUE TITLE
Reducing collision box on containers breaks other mods

### ISSUE THREAD

**Issue by jimmyjon711** [jimmyjon711/FactorioExtended-Plus-Storage#2]
https://mods.factorio.com/mod/FactorioExtended-Plus-Storage/discussion/5a9b5117e80fe30009820071

**Comment by dgw** [comment]
I skimmed through the prototype definitions, and it looks like the collision box defined in the offending function is already set on the mod-added entities. So the loops are only meant to fixup the collision boxes of entities from other mods (including `base`).

There are a couple options besides just removing it. Instead of just blindly overriding the `collision_box` for every entity in the `container` and `logistic-container` groups, you could just go through the list of known base-game entities (obviously wouldn't address mods that add other safe, 1x1 chests). Or you could check the collision box (or selection box) before overriding it and only override if it's the same as (or within some tolerance of) what you expect for a 1x1 chest entity.

It might be simplest to let the collision box adjustment go, though, you're right.

**Comment by jimmyjon711** [comment]
Yes it is set for the modded chests, I was just trying to change the vanilla ones and I didn't think through it fully. So I am going to remove the code that iterates though all containers. If someone really wants to walk though chests there is another mod for that :-).
